<?php

namespace ContainerKslNthQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSpamCheckerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\SpamChecker' shared autowired service.
     *
     * @return \App\SpamChecker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/SpamChecker.php';

        return $container->privates['App\\SpamChecker'] = new \App\SpamChecker(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), $container->getEnv('AKISMET_KEY'));
    }
}
