<?php

namespace ContainerZy5jiLb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R8CFNWy.App\Entity\Page' shared service.
     *
     * @return \App\Entity\Page
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.R8CFNWy": it references class "App\\Entity\\Page" but no such service exists.');
    }
}
