<?php

namespace ContainerZpgTt8I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M1u4WEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m1u4WE_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m1u4WE_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'medicamentRepository' => ['privates', 'App\\Repository\\MedicamentRepository', 'getMedicamentRepositoryService', true],
            'page' => ['privates', '.errored..service_locator.m1u4WE_.App\\Entity\\Page', NULL, 'Cannot autowire service ".service_locator.m1u4WE_": it references class "App\\Entity\\Page" but no such service exists.'],
            'twig' => ['services', '.container.private.twig', 'get_Container_Private_TwigService', false],
            'user' => ['privates', '.errored..service_locator.m1u4WE_.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.m1u4WE_": it references class "App\\Entity\\User" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'medicamentRepository' => 'App\\Repository\\MedicamentRepository',
            'page' => 'App\\Entity\\Page',
            'twig' => '?',
            'user' => 'App\\Entity\\User',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
