<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHVxD2b9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHVxD2b9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHVxD2b9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHVxD2b9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHVxD2b9\App_KernelDevDebugContainer([
    'container.build_hash' => 'HVxD2b9',
    'container.build_id' => 'c89a478d',
    'container.build_time' => 1622090701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHVxD2b9');
