<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCkOPmWN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCkOPmWN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCkOPmWN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCkOPmWN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCkOPmWN\App_KernelDevDebugContainer([
    'container.build_hash' => 'CkOPmWN',
    'container.build_id' => '1927e7fc',
    'container.build_time' => 1650712891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCkOPmWN');
