<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH5NnxVd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH5NnxVd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH5NnxVd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH5NnxVd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH5NnxVd\App_KernelDevDebugContainer([
    'container.build_hash' => 'H5NnxVd',
    'container.build_id' => 'e9efcd05',
    'container.build_time' => 1650645624,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH5NnxVd');
