<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '../../node_modules/babel-polyfill/dist/polyfill.js',
                '../../node_modules/wikiquote-api/src/WikiquoteApi.module.mjs',
                'build/js/jquery-3.6.0.min.js',
                '/build/runtime.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_core-js_modules_es_ob-7db861.js',
                '/build/app.js',
                'build/js/bootstrap.js',
                '/build/js/bootstrap.bundle.js',
                '/build/highcharts.js',
            ],
            'css' => [
                '/build/css/bootstrap.css',
                'https://fonts.googleapis.com/css2?family=Lobster+Two&family=Source+Sans+Pro&display=swap',
                '/build/app.css',
                '/build/iphone.css',
            ],
        ],
    ],
],

]];
