<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/js/jquery.min.js',
                '/build/js/jquery.dropotron.js',
                '/build/js/browser.js',
                '/build/js/breakpoints.js',
                '/build/js/util.js',
                '/build/js/main.js',
                '/build/runtime.js',
                '/build/vendors-node_modules_symfony.js',
                '/build/app.js',
                '/build/js/bootstrap.min.js',
                '/build/js/bootstrap.bundle.js',
            ],
            'css' => [
                '/build/css/bootstrap.min.css',
                'https://fonts.googleapis.com/css2?family=Lobster+Two&family=Sacramento&display=swap',
                'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300italic,600,600italic&display=swap',
                '/build/css/fontawesome-all.min.css',
                '/build/css/main2.css',
            ],
        ],
    ],
],

]];
