<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/js/jquery.min.js',
                '/build/js/jquery.dropotron.min.js',
                '/build/js/browser.min.js',
                '/build/js/breakpoints.min.js',
                '/build/js/util.js',
                '/build/js/main.js',
                '/build/runtime.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_core-js_modules_es_ob-7db861.js',
                '/build/app.js',
                '/build/js/bootstrap.js',
                '/build/js/bootstrap.bundle.js',
            ],
            'css' => [
                '/build/css/bootstrap.css',
                'https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap',
                '/build/css/main.css',
                '/build/css/fontawesome-all.min.css',
            ],
        ],
    ],
],

]];
